@startuml
!theme plain

left to right direction
skinparam linetype ortho

hide empty members
hide circle


class ConfluenceContentModel{
List<ConfluencePage> pages
}

class ConfluencePage {
    String title
    Type type
    String contentFilePath
    List<ConfluencePage> children
    Map<String, String> attachments
    List<String> labels
}

ConfluenceContentModel::pages-{ConfluencePage: consist of

ConfluencePage::type--Type
enum Type{
STORAGE,
WIKI,
VIEW
}


@enduml